### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/navigation_array#30]
Fehlermeldung unexpected token "->"

Bei der Ausgabe der Navigation über
`$NavigationArray =  new BuildArray(0, 3)->generate();`

wird bei mir der Fehler unexpected token "->" gewhoopst. Das ist in der Dokumentation offenbar nicht korrekt.

Mit diesem Code geht es:

`$NavigationArray =  new BuildArray(0, 3);
$result = $NavigationArray->generate();
$navigationList = generateNavigationList($result);
`

Edit: in der Beschreibung für die Bootstrap-Navi gibt es einen Vertipper, da fehlt eine Klammer:
` <?php echo bsnavi5(navArray($NavigationArray) ?>`

auch hier komme ich erst zu einem Ergebnis mit folgendem Code:

`$NavigationArray =  new BuildArray(0, 3);
$result = $NavigationArray->generate(); 
$navigationList = bsnavi5(navArray($result));`

Gruß
Heinz

**Comment by skerbis** [comment]
Danke. Update ist unterwegs
