### ISSUE TITLE
noch Fehler

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/navigation_array#31]
Das AddOn sieht vielversprechend aus, leider gibt es noch kleine Fehler:

1) noch ein Klammerfehler beim Beispiel UIkit-Drop-Down:

`$navigation = '<ul class="uk-navbar-nav">'. myNavi_demo(navArray($NavigationArray) .'</ul>';`
Bitte die anderen Beispiele auch überprüfen ...

2) Bei bsnavi5 Bootstrap-Navigation, aber auch bei UIkit:

`<?php echo bsnavi5(navArray($NavigationArray)) ?>` 

das navArray scheint hier falsch zu sein, es wird bei mir die Home-Kategorie wiederholt und keine Dropdowns erzeugt.

`<?php echo bsnavi5($NavigationArray) ?>`

erzeugt die Navbar korrekt.

Wäre es noch möglich, ab der zweiten Ebene auch noch carets und Dropdowns generieren zu lassen?

Beste Grüße Heinz

**Comment by skerbis** [comment]
@erraiva  hi. Das sind alles nur Beispielen die dabei helfen sollen sich selbst eine Navigation auf Basis des Arrays zu bauen. Sinn des Addons ist es das Array zu liefern. Nicht die Navigation. Danke für die Hinweise. Ich werde es beherzigen und einpflegen. Ich selber nutze diese Beispiele nicht.
