### ISSUE TITLE
Error: Cannot use object of type rex_category as array bei Verwendung des Beispiels Breadcrumb

### ISSUE THREAD

**Issue by screenfox** [FriendsOfREDAXO/navigation_array#38]
Beim Einfügen des Breadcrump-Beispiels aus der Dokumentation in ein Modul führt dies zu einem Whoops. Es wird auf die Zeile mit return $cat['active']; verweisen.

`<?php
function bc_uikit($data = array())
{
    $output = []; // Initialisierung der Output-Variable
    foreach ($data as $cat) {
        $subnavi = ''; // Initialisierung der Subnavigation
        if ($cat['hasChildren']) {
            // Rekursiver Aufruf für Unterkategorien
            $sub = bc_uikit($cat['children']);
            $subnavi = join("\n", $sub);
        }
        $url = ' href="'.$cat['url'].'"';
        $liclass = '';
        if ('REX_ARTICLE_ID' == $cat['catId']) {
            $liclass = ' class="uk-disabled" aria-current="page"';
            $url = '';
        }
        $catname = '<a'.$url.'>'.$cat['catName'].'</a>';
        
        $output[] = '<li'.$liclass.'>' . $catname .'</li>'.$subnavi;
    }
    return implode("\n", $output);
}

// Breadcrumb erzeugen
use FriendsOfRedaxo\NavigationArray\BuildArray;
$NavigationArray = new BuildArray(0, 4, 20);
$result = $NavigationArray->setCategoryFilterCallback(function ($cat) {
        // Nur aktive Kategorien auswählen
        return $cat['active'];
})->generate();
echo '
    <nav aria-label="Breadcrumb">
    <ul class="uk-breadcrumb">'
    . bc_uikit($result) .
    '</ul>
    </nav>
';

?>`

REDAXO: 5.18.0
PHP: 8.2.24
Database: MariaDB 10.5.26
Browser: Firefox

**Did it whoops? / Whoops erhalten?**

**Error:** Cannot use object of type rex_category as array
**File:** rex:///module/7/output
**Line:** 30

<details>
<summary>Stacktrace</summary>

| Function                                             | File                                                                     | Line     |
| ---------------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| rex_article_content->{closure}                       | redaxo/src/addons/navigation_array/lib/NavigationArray/BuildArray.php    | 141      |
| FriendsOfRedaxo\NavigationArray\BuildArray->generate | rex:///module/7/output                                                   | 31       |
| require                                              | redaxo/cache/addons/structure/7.1.content                                | 363      |
| require                                              | redaxo/src/addons/structure/plugins/content/lib/article_content.php      | 122      |
| rex_article_content->getArticle                      | rex:///template/2                                                        | 218      |
| require                                              | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 443      |
| rex_article_content_base->{closure}                  | redaxo/src/core/lib/util/timer.php                                       | 56       |
| rex_timer::measure                                   | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 440      |
| rex_article_content_base->getArticleTemplate         | redaxo/src/addons/structure/plugins/content/boot.php                     | 58       |
| rex_package::{closure}                               | redaxo/src/core/lib/extension.php                                        | 52       |
| rex_extension::{closure}                             | redaxo/src/core/lib/util/timer.php                                       | 56       |
| rex_timer::measure                                   | redaxo/src/core/lib/extension.php                                        | 42       |
| rex_extension::registerPoint                         | redaxo/src/core/frontend.php                                             | 22       |
| require                                              | redaxo/src/core/boot.php                                                 | 157      |
| require                                              | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.18.0, PHP 8.2.24, MariaDB 10.5.26)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.18.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.24     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.5.26 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/131.0 |
|      Protocol | HTTP/2.0      |
|         HTTPS | yes           |

| Packages                |            |
| ----------------------: | :--------- |
|                  backup | 2.9.1      |
|             be_branding | 1.8.1      |
|                be_style | 3.5.0      |
|     be_style/customizer | 3.5.0      |
|         be_style/redaxo | 3.5.0      |
|                 bloecks | 4.0.2      |
|        bloecks/cutncopy | 4.0.2      |
|       bloecks/dragndrop | 4.0.2      |
|          bloecks/status | 3.1.1      |
|                    cke5 | 6.1.0      |
|                 cronjob | 2.11.0     |
|  cronjob/article_status | 2.10.0     |
| cronjob/optimize_tables | 2.10.0     |
|                 install | 2.12.1     |
|                  mblock | 3.4.13     |
|           media_manager | 2.17.0     |
|               mediapool | 2.15.0     |
|                metainfo | 2.11.0     |
|                   mform | 8.0.4      |
|             multiupload | 2.1.3      |
|        navigation_array | 5.1.0      |
|               phpmailer | 2.14.0     |
|                 project | dev        |
|        quick_navigation | 8.1.3      |
|               structure | 2.17.2     |
|       structure/content | 2.17.2     |
|       structure/history | 2.17.0     |
|                   users | 2.11.0     |
|                    ycom | 4.3.0      |
|               ycom/auth | 4.3.0      |
|               ycom/docs | 4.0.3      |
|              ycom/group | 4.3.0      |
|         ycom/media_auth | 4.3.0      |
|                   yform | 4.2.1      |
|             yform/email | 4.2.1      |
|           yform/manager | 4.2.1      |
|             yform/tools | 4.2.1      |
|   yform_spam_protection | 1.2.5      |
|                yrewrite | 2.10.0     |

</details>

**Comment by skerbis** [comment]
Ich habe eine neue breadcrumb Demo in der readme erdtellt. Danke für die Info
