### ISSUE TITLE
Ycom Rechte werden bei Unterseiten nicht berücksichtigt, wenn übergeordnete Kategorie mit Zugriff für alle User definiert wurde

### ISSUE THREAD

**Issue by screenfox** [FriendsOfREDAXO/navigation_array#39]
Beschreibung: Ycom Rechte werden bei Unterseiten nicht berücksichtigt, wenn übergeordnete Kategorie mit "Zugriff für alle User" definiert wurde. 
Eine Hauptmenu-Kategorie hat als Community Zugriffsrechte "Zugriff für alle User"
Eine untergeordnete Kategorie hat als Community Zugriffsrechte "Zugriff für alle nicht eingeloogten User"
Die untergeordnete Kategorie wird dennoch im eingeloggten, wie auch im nicht eingeloggten Zustand ausgegeben.

Version: navigation_array 5.1.0

**Comment by skerbis** [comment]
Ich glaube das ist richtig so. Wenn du bereits die komplette Kategorie freigegeben hast, dann gilt dieses Recht für alle Unterkategorien. Ich Check das aber noch mal. Hier verwende ich ja eine Methode aus ycom selbst.

**Comment by screenfox** [comment]
Wenn Unterseiten aber nur für eine oder verschiedene Benutzgruppen zugänglich sein sollen, dann sollte dies auch beachtet werden.
-------- Ursprüngliche Nachricht --------Von: Thomas Skerbis ***@***.***> Datum: 17.11.24  18:22  (GMT+01:00) An: FriendsOfREDAXO/navigation_array ***@***.***> Cc: screenfox ***@***.***>, Author ***@***.***> Betreff: Re: [FriendsOfREDAXO/navigation_array] Ycom Rechte werden bei Unterseiten nicht berücksichtigt, wenn übergeordnete Kategorie mit Zugriff für alle User definiert wurde (Issue #39) 
Ich glaube das ist richtig so. Wenn du bereits die komplette Kategorie freigegeben hast, dann gilt dieses Recht für alle Unterkategorien. Ich Check das aber noch mal. Hier verwende ich ja eine Methode aus ycom selbst.

**Comment by skerbis** [comment]
Ich untersuche das. Keine Sorge.

**Comment by skerbis** [comment]
@screenfox bitte den aktuellen Githubstand testen

**Comment by skerbis** [comment]
Sollte jetzt passen. Wenn nicht, bitte melden @screenfox
