### ISSUE TITLE
Fehler in BS5 Navigation Rekursion

### ISSUE THREAD

**Issue by gupi** [FriendsOfREDAXO/navigation_array#7]
`<?php bsnavi5(navArray($start = 0, $depth = 3, true)) ?>`
 führt zu gar nichts ohne echo Befehl:
`<?php echo bsnavi5(navArray($start = 0, $depth = 3, true)) ?>`

Die Bootstrap Klassen werden dem <li> Tag innerhalb eines Sub-Menüs falsch zugewiesen, wenn das wiederum Sub-Menüs enthält.
```
<ul class="navbar-nav me-auto mb-2 mb-md-0">
  <li class="nav-item"><a class="nav-link" href="/rezeption/">Rezeption</a></li>
  <li class="nav-item"><a class="nav-link" href="/buchhaltung/">Buchhaltung</a></li>
  <li class="nav-item dropdown"><a class="nav-link dropdown-toggle active show" href="/coaching/" id="ddm9" data-bs-toggle="dropdown" aria-expanded="true">Coaching</a>
  <ul class="dropdown-menu show" data-bs-popper="static">
    <li class="nav-item"><a class="nav-link active" href="/coaching/lerntherapie/">Lerntherapie</a>
      <ul>
        <li class="nav-item"><a class="nav-link" href="/coaching/lerntherapie/dyslexie/">Dyslexie</a></li>
        <li class="nav-item"><a class="nav-link" href="/coaching/lerntherapie/dyscalculie/">Dyscalculie</a></li>
      </ul>
    </li>
    <li class="nav-item dropdown"><a class="dropdown-item" href="/coaching/nachhilfe/">Nachhilfe</a></li>
 </ul>
 </li>
 <li class="nav-item"><a class="nav-link" href="/verwaltung/">Verwaltung</a></li>
 <li class="nav-item"><a class="nav-link" href="/technik/">Technik</a></li>			
</ul>
```
So sieht die HTML Ausgabe aus

**Comment by skerbis** [comment]
@gupi im code steht aber nicht: 

`<?php bsnavi5(navArray($start = 0, $depth = 3, true)) ?>`

🥹

**Comment by gupi** [comment]
Damit hast du sicher recht. Da ich, aus gutem Grund, short tags nie benutze habe ich die Schreibweise übersehen. Allerdings sollten Beispiele hier (bei Redaxo) sowas nicht enthalten! Siehe: [PHP Doku](https://www.php.net/manual/en/language.basic-syntax.phptags.php)

**Comment by gupi** [comment]
die Addon Funktion navArray(...) liefert genau das was sie soll, hier steckt kein Fehler.
Der Knackpunkt ist die recursion in bsnavi5(...) da geht etwas durcheinander bei der Klassenzuweisung für die `<li>` Tags.
so sieht die HTML-Ausgabe aus:

`<ul class="navbar-nav me-auto mb-2 mb-md-0">`
`	<li  class="nav-item dropdown">`
`		<a class="nav-link dropdown-toggle" href="[/rezeption/](view-source:https://institut.lern-fit.de/rezeption/)"id="ddm7" data-bs-toggle="dropdown">`
`			Rezeption`
`		</a>`
`		<ul class="dropdown-menu">`
`			<li  class="nav-item dropdown">`
`				<a class="dropdown-item" href="[/rezeption/belegungsplan/](view-source:https://institut.lern-fit.de/rezeption/belegungsplan/)">`
`					Belegungsplan`
`				</a>`
`			</li>`
`			<li  class="nav-item dropdown">`
`				<a class="dropdown-item" href="[/rezeption/neuanmeldung/](view-source:https://institut.lern-fit.de/rezeption/neuanmeldung/)">`
`					Neuanmeldung`
`				</a>`
`			</li>`
`		</ul>`
`	</li>`
`	<li  class="nav-item dropdown">`
`		<a class="nav-link dropdown-toggle" href="[/buchhaltung/](view-source:https://institut.lern-fit.de/buchhaltung/)"id="ddm8" data-bs-toggle="dropdown">`
`			Buchhaltung`
`		</a>`
`		<ul class="dropdown-menu">`
`			<li  class="nav-item dropdown">`
`				<a class="dropdown-item" href="[/buchhaltung/faktura/](view-source:https://institut.lern-fit.de/buchhaltung/faktura/)">`
`					Faktura`
`				</a>`
`			</li>`
`			<li  class="nav-item dropdown">`
`				<a class="dropdown-item" href="[/buchhaltung/mahnwesen/](view-source:https://institut.lern-fit.de/buchhaltung/mahnwesen/)">`
`					Mahnwesen`
`				</a>`
`			</li>`
`			<li  class="nav-item dropdown">`
`				<a class="dropdown-item" href="[/buchhaltung/zahlungsverfolgung/](view-source:https://institut.lern-fit.de/buchhaltung/zahlungsverfolgung/)">`
`					Zahlungsverfolgung`
`				</a>`
`			</li>`
`		</ul>`
`	</li>`
`	<li  class="nav-item dropdown">`
`		<a class="nav-link dropdown-toggle" href="[/coaching/](view-source:https://institut.lern-fit.de/coaching/)"id="ddm9" data-bs-toggle="dropdown">`
`			Coaching`
`		</a>`
`		<ul class="dropdown-menu">`
`			<li  class="nav-item">` **ist fehlerhaft, hätte "nav-item dropdown" heißen müssen**
`				<a class="nav-link" href="[/coaching/lerntherapie/](view-source:https://institut.lern-fit.de/coaching/lerntherapie/)">` **Darf kein "nav-link" sein sondern ein "nav-link dropdown-toggle"**
`					Lerntherapie`
`				</a>`
`				<ul>`
`					<li  class="nav-item">`
`						<a class="nav-link" href="[/coaching/lerntherapie/dyslexie/](view-source:https://institut.lern-fit.de/coaching/lerntherapie/dyslexie/)">`
`							Dyslexie`
`						</a>`
`					</li>`
`					<li  class="nav-item">`
`						<a class="nav-link" href="[/coaching/lerntherapie/dyscalculie/](view-source:https://institut.lern-fit.de/coaching/lerntherapie/dyscalculie/)">`
`							Dyscalculie`
`						</a>`
`					</li>`
`				</ul>`
`			</li>`
`			<li  class="nav-item dropdown">` **Was oben fehlt, wurde fälschlicherweise hier eingefügt**
`				<a class="dropdown-item" href="[/coaching/nachhilfe/](view-source:https://institut.lern-fit.de/coaching/nachhilfe/)">`
`					Nachhilfe`
`				</a>`
`			</li>`
`		</ul>`
`	</li>`
`	<li  class="nav-item">`
`		<a class="nav-link" href="[/verwaltung/](view-source:https://institut.lern-fit.de/verwaltung/)">`
`			Verwaltung`
`		</a>`
`	</li>`
`	<li  class="nav-item">`
`		<a class="nav-link active" href="[/technik/](view-source:https://institut.lern-fit.de/technik/)">`
`			Technik`
`		</a>`
`	</li>`
`</ul>`
`		<a class="nav-link active" href="[/technik/](view-source:https://institut.lern-fit.de/technik/)">`
`			Technik`
`		</a>`
`	</li>`
`</ul>`

**Comment by gupi** [comment]
Ich denke ich habe alle Infos nach bestem Wissen und Gewissen bereitgestellt. Den Fehler in der Recursion werde ich aus Zeitgründen nicht suchen können.

**Comment by skerbis** [comment]
Danke @gupi. Da ich kein BS5 - Nutzer bin hoffe ich auf Hilfe von außen. Ich weiß nicht wie die einzelnen Classes aussehen müssen.

**Comment by gupi** [comment]
Natürlich will ich helfen wo ich kann, klar muss sein, dass es hier um zwei Aspekte geht:

1. Die richtigen BS5 Klassen müssen identifiziert werden, falls damit allein das Nesting von Menüs organisiert werden kann. Hier glaube ich aber mitlerweile, dass Stefan Dannfeld richtig liegt und JS benötigt wird. Daran arbeite ich gerade und gebe mein Wissen und meine Erkenntnisse gerne weiter, sobald ich eine funktionierende Lösung habe.
**mein aktueller Kenntnisstand:**
> `<li>`-tags die "master" eines Submenüs sind, müssen der Klasse "dropdown" angehören. Der `<a>`-tag muss der Klasse "dopdown-item" angehören. 
2. Das, was in der recursion passiert ist: hier werden schlicht die Klassen den falschen li-Tags zugewiesen.

**Comment by skerbis** [comment]
1. alles ok. Ist ja nicht Problem des AddOns. 
2. ich schau mal dass ich neue Beispiele entwickle. Das hier ist innerhalb einer Slack-session entwickelt worden. Vielleicht schmeiss ich's komplett raus und versuche die Rekursion einfach für eine einfache Navi zu erklären.

**Comment by skerbis** [comment]
Ich mache hier erstmal dicht.
https://github.com/FriendsOfREDAXO/navigation_array/issues/8
